### ISSUE TITLE
getting error during starting

### ISSUE THREAD

**Issue by hbakhtiyor** [penpot/penpot#35]
I got the error in figweel(#1) tmax screen

```
Saving to: ‘/home/uxbox/.lein/self-installs/leiningen-2.7.1-standalone.jar.pending’

/home/uxbox/.lein/self-installs/leini 100%[=======================================================================>]  14.66M   136KB/s    in 3m 5s   

2017-01-20 14:43:01 (81.2 KB/s) - ‘/home/uxbox/.lein/self-installs/leiningen-2.7.1-standalone.jar.pending’ saved [15370238/15370238]

Could not transfer artifact lein-ancient:lein-ancient:pom:0.6.10 from/to clojars (https://clojars.org/repo/): Specified destination directory cannot be created: /home/uxbox/.m2/repository/lein-ancient/lein-ancient/0.6.10
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/home/uxbox/.nvm/versions/node/v6.9.1/bin/node" "/home/uxbox/.nvm/versions/node/v6.9.1/bin/npm" "run" "figwheel"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! uxbox@0.1.0 figwheel: `PATH=./scripts:$PATH ./scripts/build-worker && PATH=./scripts:$PATH ./scripts/figwheel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uxbox@0.1.0 figwheel script 'PATH=./scripts:$PATH ./scripts/build-worker && PATH=./scripts:$PATH ./scripts/figwheel'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uxbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     PATH=./scripts:$PATH ./scripts/build-worker && PATH=./scripts:$PATH ./scripts/figwheel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uxbox
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uxbox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/uxbox/uxbox/frontend/npm-debug.log
uxbox@44074e1b6533:~/uxbox/frontend$
```

and backend(#2) tmax screen too

```
uxbox@44074e1b6533:~/uxbox/backend$ ./scripts/run.sh 
Could not transfer artifact lein-ancient:lein-ancient:pom:0.6.10 from/to clojars (https://clojars.org/repo/): Specified destination directory cannot be created: /home/uxbox/.m2/repository/lein-ancient/lein-ancient/0.6.10
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Comment by niwinz** [comment]
Seems like you hace network issues.

**Comment by hbakhtiyor** [comment]
but it can download another dependencies

**Comment by niwinz** [comment]
Yeah, but without more context, the error message says that. Take care that many dependencies are fetched from maven and not from clojars.

Try removing the ancient plugin on the project.clj/profiles.clj file

**Comment by hbakhtiyor** [comment]
what to add instead of them?

**Comment by niwinz** [comment]
nothing, is just a plugin to lein that is used occasionally for check outdated dependencies. You don't need it on the basis use case.

**Comment by hbakhtiyor** [comment]
still the same

**Comment by studiospring** [comment]
I'm having the same problem with same error message. I doubt it is network issues because I can access clojars.org and I don't have a proxy. It does not work even if I manually create the directory.

I too have deleted profiles.clj, nothing changes.

**Comment by niwinz** [comment]
I suspect is because the $HOME/.m2 directory does not exists on the host machine. Try executing `mkdir -p ~/.m2` with the user that you are using to execute the `./manage.sh run`.

If that does not works, try removing the following line https://github.com/uxbox/uxbox/blob/master/manage.sh#L26

**Comment by stephenmoloney** [comment]
It seems that the manage.sh script sets the `~/.m2` folder to root.
***sudo chown user:group -R ~/.m2 && ./manage.sh run***
fixed it for me. 

So I can open up uxbox now. This is quite amazing that you can get this much functionality in a browser... And writing it in clojurescript must have been a real challenge but +1 for functional programing on the frontend.

**Comment by niwinz** [comment]
Many thanks @stephenmoloney 

In my opinion, writing that in js will be a much bigger challenge :P

**Comment by hbakhtiyor** [comment]
also can run it, thanks

btw, what do you think about https://github.com/precursorapp/precursor, they use the same stacks

**Comment by parthmewada** [comment]
as per @stephenmoloney i tired changing the ownership to uxbox nothing happened, tried to run with root user same issue. @stephenmoloney @niwinz i m attaching the error i have got, Please for god sake have a look on the same and update me wats the issue. i m tried to reach @niwinz but seems he is not replying. 


![1](https://cloud.githubusercontent.com/assets/23476049/23013354/4723db14-f450-11e6-91fc-f4d9f4e77fee.JPG)

**Comment by niwinz** [comment]
I'm traveling right now.

Please don run random commands using root user.

This error does not make sense if yo execute everything as is expected to
be executed. Right now that error is because no npm modules are
installed... 'npm install' should solve it.

But my recomendation is repat all the process from zero (cloning again a
clean copy of the repo) and execute './manage.sh run'. Seems le yo have the
directory in inconsistent state and/or inconsistent permissions.

On Feb 16, 2017 9:30 AM, "parthmewada" <notifications@github.com> wrote:

as per @stephenmoloney <https://github.com/stephenmoloney> i tired changing
the ownership to uxbox nothing happened, tried to run with root user same
issue. @stephenmoloney <https://github.com/stephenmoloney> @niwinz
<https://github.com/niwinz> i m attaching the error i have got, Please for
god sake have a look on the same and update me wats the issue. i m tried to
reach @niwinz <https://github.com/niwinz> but seems he is not replying.

[image: 1]
<https://cloud.githubusercontent.com/assets/23476049/23013354/4723db14-f450-11e6-91fc-f4d9f4e77fee.JPG>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/uxbox/uxbox/issues/35#issuecomment-280265955>, or mute
the thread

**Comment by parthmewada** [comment]
Thanks @niwinz for the reply, can you please guide like if i just run manage.sh, what permission i have to give *uxbox* ownership as user...??

**Comment by parthmewada** [comment]
@stephenmoloney  Hii Can you please help me as i have changed the ownership still the same error figwheel is unable to start. backend and services started, gulp installed (Had to done manually), but throwing error as below

module.js:471
    throw err;
    ^

Error: Cannot find module 'run-sequence'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/uxbox/uxbox/frontend/gulpfile.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
