### ISSUE TITLE
Option to completely disable local login and only allow configured oauth providers

### ISSUE THREAD

**Issue by violoncelloCH** [penpot/penpot#555]
**Is your feature request related to a problem? Please describe.**
I've a selfhosted gitlab instance with only trusted users which chould be the only ones able to login (register) in penpot. Registration is also disabled on the backend.

**Describe the solution you'd like**
Therefore it would be nice to have a config.js var to completely hide the default login, so only "Login with GitLab " would be available.

**Describe alternatives you've considered**
manually patch the frontend code to hide the login form, not really elegant tho

**Comment by niwinz** [comment]
Nice one! I have created this [taiga issue](https://tree.taiga.io/project/penpot/issue/1200) for properly track it.

**Comment by niwinz** [comment]
This should be fixed.

**Comment by violoncelloCH** [comment]
I'm sorry to come back to this, but I just went through the documentation (https://help.penpot.app/technical-guide/configuration/) and the sample config.env file (https://github.com/penpot/penpot/blob/develop/docker/images/config.env) and I can't find a way to disable the login (so that the login form is removed/hidden and only oauth provider login buttons remain)...
could you clarify how to achieve this?
I've also tried if adding a (maybe undocumented) flag to `PENPOT_FLAGS=` does the trick: I've tried `disable-login disable-local-login disable-login-with-ldap` but they all didn't help - the login form stays visible above the "Login with Gitlab" button

**Comment by niwinz** [comment]
oh, sorry for the confusion, I think this issue is closed on a quick review on what we have closed on the taiga side.
there are no way to disable login completely; right now we have implemented is disabling "registration" using penpot, this means you will still have this pages active, but users cant register, and then, they will not be able to login.

The registration can be disabled with `disable-registration` flag. As I said, it deactivates registration on backend side only, so frontend  application still has the register page accesible (but does not work on submit).

**Comment by violoncelloCH** [comment]
I see... makes sense...
would you mind reopening this issue then, as it's not yet solved in that case...?

**Comment by niwinz** [comment]
This issue is solved, this issue si about disabling the register, we already have opened internally enhancement for disable the UI when flag is set.

**Comment by violoncelloCH** [comment]
hmm, I guess that's a misunderstanding then... (in my opinion, what I explain in the title and description of this issue (hiding the login form in the UI) is not yet implemented, so it feels weird to me this is closed)

but cool that you already have a ticket for this internally :)
One thing to keep in mind for this is that it could make sense to have two settings, one for registration and one for login. There might be a use-case for letting some users register and then closing registration. In that case the login-form should stay available while for my use-case (only OAuth users), also the login-form should be hidden,

**Comment by nhh** [comment]
@niwinz I agree with @violoncelloCH it seems that here is a misunderstanding.

For people that have oidc configured, it is very useful to visually disable (hide) the login boxes.

Our users dont know what to put in the fields, they are also not technical and don't immediatly connecting "Einloggen mit OpenID Connect" with the company preferred way of logging in.

So the the best solution for this, would be to provide a configuration like `disable-local-login` which simply hides the input and just shows the sso options.

<img width="449" alt="Bildschirmfoto 2022-04-04 um 14 20 34" src="https://user-images.githubusercontent.com/13472382/161542311-96f92eaf-a550-4e88-ba61-393584243408.png">

The alternative is, that I have to somewho inject custom css into that site.

**Comment by niwinz** [comment]
Agree, and we have fixed it for the next release, now you will be able to visually disable the password flow.

**Comment by nhh** [comment]
Awesome thank you! 🎉😇
